spring:
  application:
    name: rocketmq-consumer
  cloud:
    stream:
      bindings:
        input: {content-type: application/json,destination: test-topic,group: test-group}
      rocketmq:
        binder:
          name-server: 192.168.72.128:9876
server:
  port: 9093
